#!/bin/bash
# -*- bash -*-

: << =cut

=head1 NAME

arris-sb6190-snr - Plugin to measure Corrected on Arris Modem

=head1 NOTES

Uses default IP address and status pages for modem

=head1 AUTHOR

Peter Morton

=head1 LICENSE

GPLv2

=head1 MAGIC MARKERS

 #%# family=auto
 #%# capabilities=autoconf

=cut

. $MUNIN_LIBDIR/plugins/plugin.sh

if [ "$1" = "autoconf" ]; then
        echo yes
        exit 0
fi

if [ "$1" = "config" ]; then
	  echo "graph_title Arris SB6190 Corrected Packets"
          echo "graph_period minute"
	  echo "graph_vlabel corrected / ${graph_period}"
	  echo "graph_scale no"
	  echo "graph_total Total"
	  echo "graph_category arris"
          for i in {1..28};
	  do
		echo "downcorrected${i}.label Downstream ${i}"
		echo "downcorrected${i}.type COUNTER"
		if [ "${i}" = "1" ]; then
			echo "downcorrected${i}.draw AREA" 
		else 
			echo "downcorrected${i}.draw STACK"
		fi
          done
	  exit 0;
fi

dl_status="`wget -q -O - http://192.168.100.1/cgi-bin/status | grep 256QAM`"

echo $dl_status | sed -e 's/\/tr>/tr>\n/g' | while read -r line; do

  if [ ! -z "$line" ]; then
     channel="`echo $line | xmllint --html -xpath "//tr/td[1]/text()" - `"
     corrected="`echo $line | xmllint --html -xpath "//tr/td[8]/text()" - `"
     echo downcorrected${channel}.value ${corrected}
  fi

done 


#Channel
#Lock_Status  
#Modulation  
#Channel_ID  
#Frequency  
#Power  
#SNR  
#Corrected  
#Uncorrectables
